change tests
nataliaruzhytska/My-Repository pull request #1
Opened 2019-09-24 19:24 UTC by nataliaruzhytska

2019-09-27 11:25 UTC, dimigor commented
You should follow PEP8. For example between two functions have to be two blank lines

2019-09-27 11:26 UTC, dimigor commented on git/homework.py
> +    for i in range(26):
try to iterate over `string.ascii_lowercase`

2019-09-27 16:01 UTC, nataliaruzhytska commented on git/homework.py
> +    for i in range(26):
Исправила

2019-09-28 09:39 UTC, yuriimchg requested changes
перевірив роботу
завдання виглядають дуже класно
деякі дуже оригінальні
але в мене є декілька зауважень, які я залишив біля завдань
також є деякі зауваження до стилізації, які порушують стандарти PEP-8
наприклад, відстань між імпортами і оголошенням коду має бути 2 рядки, а не 3
для того, щоб бачити всі ці штуки, раджу використовувати `flake8`

2019-09-28 09:39 UTC, yuriimchg commented on git/homework.py
> +    except ValueError:
```suggestion
    except TypeError:
        raise ValueError("Not valid input data")
```

2019-09-28 09:39 UTC, yuriimchg commented on git/homework.py
> +    l.remove(7)
дуже цікаве рішення

2019-09-28 09:39 UTC, yuriimchg commented on git/homework.py
> +        if i > 0:
тут варто врахувати, що нуль також може входити в цей список

2019-09-28 12:03 UTC, nataliaruzhytska commented on git/homework.py
> +        if i > 0:
Спасибо, исправила

2019-09-28 12:25 UTC, yuriimchg approved these changes
молодець :+1: 
вітаю з виконаним домашнім :muscle: :fire: :tada: :dancer:

2019-09-28 20:32 UTC, merged