Flask lesson2
nataliaruzhytska/My-Repository pull request #10
Opened 2019-11-04 14:09 UTC by nataliaruzhytska

2019-11-04 15:41 UTC, dimigor requested changes

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/main
> +from datetime import timedelta
I think this file should contain `.py` in the name

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +@products.route('/all_products', methods=['GET', 'POST'])
make different routes to HTTP methods

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +@products.route('/all_products', methods=['GET', 'POST'])
try to decrease using if/else operators

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +    d = {'id': f.id + request.form.get('name'),
do not concatenate strings with `+`. Better use `fstrings`(python3) or `.format()`(python2)

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +        data = get_data("prod.json")
make `prod.json` as constant at the bottom of file/class or create file `constants.py` if you will use it in a few modules

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +        f.save(os.path.join('/home/nataliia/homework/My-Repository/flask_lesson2/src/static',
do not hardcode this path

2019-11-04 15:41 UTC, dimigor commented on flask_lesson2/src/routes/Supermarket/supermarkets.py
> +def get_supermarket(id):
`id` is reserved python variable, name it different

2019-11-04 15:42 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +@products.route('/all_products', methods=['GET', 'POST'])
if your code will be grown, if/else statements will hard to maintain

2019-11-04 15:43 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +    d = {'id': f.id + request.form.get('name'),
It will be faster and more readable

2019-11-04 15:44 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +    d = {'id': f.id + request.form.get('name'),
also prevent TypeError like `TypeError: unsupported operand type(s) for +: 'int' and 'str'`

2019-11-05 15:56 UTC, dimigor requested changes

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +product_list = "prod.json"
constants in python defines with caps lock like `I_AM_CONSTANT`

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +products_upload = '/home/nataliia/homework/My-Repository/flask_lesson2/src/routes/Product/static'
do not hardcode this value, you may get it from os library
`os.path.dirname(os.path.abspath(__file__))` this will be path of your project root directory

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/routes/Product/products.py
> +            return render_template('product.html',
what if we cannot find any object. we need to redirect to 404 page
take a look at ` for...else`

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/routes/Product/templates/all_products.html
> +    <form action="/all_products">
`url_for`

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/routes/Supermarket/templates/add_supermarket.html
> +                <form method="POST" action="/upload" enctype="multipart/form-data">
`url_for`

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/utils.py
> +    with open(item_list) as file:
do not use `file` and etc as name of variable. It is python reserved word

2019-11-05 15:56 UTC, dimigor commented on flask_lesson2/src/utils.py
> +    with open(item_list) as file:
also you need to catch Value and IOError

2019-11-05 20:44 UTC, nataliaruzhytska commented on flask_lesson2/src/utils.py
> +    with open(item_list) as file:
Done

2019-11-05 20:44 UTC, nataliaruzhytska commented on flask_lesson2/src/routes/Supermarket/templates/add_supermarket.html
> +                <form method="POST" action="/upload" enctype="multipart/form-data">
Done

2019-11-05 20:44 UTC, nataliaruzhytska commented on flask_lesson2/src/routes/Product/templates/all_products.html
> +    <form action="/all_products">
Done

2019-11-05 20:44 UTC, nataliaruzhytska commented on flask_lesson2/src/routes/Product/products.py
> +            return render_template('product.html',
Done

2019-11-05 20:45 UTC, nataliaruzhytska commented on flask_lesson2/src/routes/Product/products.py
> +products_upload = '/home/nataliia/homework/My-Repository/flask_lesson2/src/routes/Product/static'
Done

2019-11-05 20:45 UTC, nataliaruzhytska commented on flask_lesson2/src/routes/Product/products.py
> +product_list = "prod.json"
Done

2019-11-06 08:08 UTC, dimigor approved these changes

2019-11-06 08:08 UTC, dimigor commented on flask_lesson2/src/utils.py
> +    except(IOError, FileNotFoundError, ValueError):
here> IOError and FileNotFound will never raised

2019-11-06 08:08 UTC, dimigor commented on flask_lesson2/src/utils.py
> +        raise
do not raise, just return empty dict

2019-11-06 09:16 UTC, merged