lesson1
nataliaruzhytska/My-Repository pull request #14
Opened 2019-12-24 18:03 UTC by nataliaruzhytska

2020-01-02 22:46 UTC, yuriimchg requested changes
переглянув, є трохи зауважень до домашнього

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/Dockerfile
> +RUN pip install django
апка не запускається, оскільки не всі залежності встановлено

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/Dockerfile
> +RUN pip install django
```suggestion
RUN pip install -r requirements.txt
```
але перед цим потрібно спочатку створити requirements.txt, а потім запхати в докер

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/lesson1/settings.py
> +ALLOWED_HOSTS = ['localhost', '0.0.0.0']
цікаво, що `localhost` парситься, а 127.0.0.1 - ні

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/lesson1/tests.py
> +POCKEMON_URL = 'https://pokeapi.co/api/v2/'
адресу бажано винести в конфіги (settings.py)

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/lesson1/tests.py
> +        self.assertEqual(response.status_code, HTTPStatus.OK)
потрійні асерти не бажано робити - краще зробити три окремі тести або параметризацію для тестів

2020-01-02 22:46 UTC, yuriimchg commented on django_lesson/lesson1/lesson1/tests.py
> +            name = [p['name'] for p in data1]
те саме

2020-01-02 23:30 UTC, nataliaruzhytska commented on django_lesson/lesson1/Dockerfile
> +RUN pip install django
Done

2020-01-03 17:01 UTC, yuriimchg approved these changes
молодець, все працює, як треба :+1:

2020-01-03 17:01 UTC, yuriimchg commented on django_lesson/lesson1/lesson1/tests.py
> +            name = [p['name'] for p in data2]
no newline at the end of file

2020-01-05 16:02 UTC, merged