answers
nataliaruzhytska/My-Repository pull request #7
Opened 2019-10-16 21:50 UTC by nataliaruzhytska

2019-10-18 08:29 UTC, dimigor requested changes

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +Используется для того, чтобы код был понятным и удобным для работы.
більше домовленість, аніж правила

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +локально (в определенном блоке кода) или глобально (доступна во всей программе)
Якщо глобально оголошена змінна, то чи можемо ми її використати та перезаписати в локальному скоупі(наприклад у функції)?

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +	pass
поясни яка різниця між args і kwargs

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +или использоваться с разными объектами.
чи можемо ми створити метод який не буде відноситись до обєкту?

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +yield возвращает генератор, не завершая цикл.
повертає обєкт не завершуючи роботу функціЇ, буде правильніше

2019-10-18 08:29 UTC, dimigor commented on theoretical_questions/1.md
> +def (a: int, b: float): -> float
чи буде працювати програма якщо передати значення не того типу, який описаний в анотації?

2019-10-18 08:55 UTC, nataliaruzhytska commented on theoretical_questions/1.md
> +локально (в определенном блоке кода) или глобально (доступна во всей программе)
Можем использовать в функции с ключевым словом global, а потом перезаписать локально, это уже будет другая переменная.

2019-10-18 08:57 UTC, nataliaruzhytska commented on theoretical_questions/1.md
> +	pass
*args используется для списков и кортежей, **kwargs - для словарей.
можно использовать другие названия, главное, * или ** вначале.

2019-10-18 09:00 UTC, nataliaruzhytska commented on theoretical_questions/1.md
> +или использоваться с разными объектами.
Можем создать метод класса (с декоратором @classmethod), он относится ко всему классу.

2019-10-18 09:14 UTC, nataliaruzhytska commented on theoretical_questions/1.md
> +def (a: int, b: float): -> float
Будет, если программа может работать с этим типом.

2019-10-21 07:05 UTC, dimigor commented on theoretical_questions/1.md
> +локально (в определенном блоке кода) или глобально (доступна во всей программе)
Насправді глобальні змінні ми можемо читати і в локальних скоупах, але щоб перезаписувати їх нам потрібен global. Але такі операції краще не робити
'global_var = 1
def some_func():
    global global_var
    global_var = 2`

2019-10-21 07:07 UTC, dimigor submitted a review, later dismissed

2019-10-21 07:46 UTC, merged