completed
nataliaruzhytska/My-Repository pull request #8
Opened 2019-10-24 09:42 UTC by nataliaruzhytska

2019-10-24 21:31 UTC, yuriimchg requested changes
привіт
загалом добре, але є зауваження стосовно навігації на сторінці

2019-10-24 21:31 UTC, yuriimchg commented on flask1/templates/home.html
> +{% endblock %}
_+_ add newline

2019-10-24 21:31 UTC, yuriimchg commented on flask1/templates/base.html
> +        <a class="nav-link" href="#">Pricing</a>
а ці лінки точно треба?
я б краще зробив <s>кращегенератор</s> лінки на `/fruits`, `/vegetables` - це дозволить легше перемикатися між ендпоінтами

2019-10-24 21:31 UTC, yuriimchg commented on flask1/templates/base.html
> +        <a class="nav-link" href="#">Home
цей лінк нікуди не редіректить

2019-10-24 21:31 UTC, yuriimchg commented on flask1/templates/base.html
> +        </div>
також не розумію функцій цього випадного меню

2019-10-25 14:00 UTC, nataliaruzhytska commented on flask1/templates/home.html
> +{% endblock %}
done

2019-10-25 14:18 UTC, nataliaruzhytska commented on flask1/templates/base.html
> +        <a class="nav-link" href="#">Pricing</a>
done

2019-10-25 14:19 UTC, nataliaruzhytska commented on flask1/templates/base.html
> +        <a class="nav-link" href="#">Home
done

2019-10-25 14:19 UTC, nataliaruzhytska commented on flask1/templates/base.html
> +        </div>
done

2019-10-26 20:03 UTC, yuriimchg approved these changes
+

2019-10-26 20:06 UTC, merged